// Code generated by Slice Machine. DO NOT EDIT.

import Nav from "./Nav";
import NavigationItem from "./NavigationItem";

export { Nav, NavigationItem };

export const components = {
  nav: Nav,
  navigation_item: NavigationItem,
};
