import { type AppType } from "next/app";

import { api } from "../utils/api";

import "../styles/globals.css";
import { Layout } from "../components/layout/Layout";
import Head from "next/head";

const App: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Ryan Spacone — Director of Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
};

export default api.withTRPC(App);
