import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import TestImage from "../../public/about.webp";

type AboutPageProps = InferGetStaticPropsType<typeof getStaticProps>;

const About: NextPage<AboutPageProps> = () => {
  return (
    <>
      <Head>
        <title>About — Ryan Spacone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-4xl">
        <Image
          src={TestImage}
          alt="About Image"
          className="mb-10 w-full"
          placeholder="blur"
        />
        Spending his formative years in the high school darkroom, Ryan
        discovered a love and affinity of using the camera for storytelling.
        Graduating from Columbia College: Chicago he focused in Cinematography
        and was given the opportunity to join Chicago’s IATSE 476 where he
        worked both Grip & Electric departments for almost a decade, training
        his eye in the art of lighting & composition.
        <br />
        <br />
        His career as a DP began in low-budget shorts, would steadily progress
        from documentary & commercial work to the eventual full length feature &
        episodic television. In 2018 his goal of becoming a cinematographer
        solidified when he joined The International Cinematographers Guild:
        Local 600.
        <br />
        <br />
        His most recent work, a 10 part mini-series called Bring on the Dancing
        Horses, premiered at Sundance Film Festival in 2022. Directed by Michael
        Polish and starring Kate Bosworth, the series follows a hitwoman
        determined to enact justice upon a group of eccentric criminals to the
        backdrop of Montana.
        <br />
        <br />
        Currently based in Los Angeles, Spacone spends much of his free-time
        hiking and camping in the mountains of California with his dog, Ginger
        where he still carries an old film camera in search of the perfect
        frame.
      </div>
    </>
  );
};

export default About;

export const getStaticProps: GetStaticProps = () => {
  return {
    props: {},
  };
};
