import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TestImage from "../../public/image.webp";
import { motion } from "framer-motion";

type IndexPageProps = InferGetStaticPropsType<typeof getStaticProps>;

const ProjectCard = ({ url, delay }: { url: string; delay: number }) => {
  return (
    <motion.div
      className="group h-auto w-full overflow-hidden"
      style={{
        y: 25,
        opacity: 0,
      }}
      animate={{
        y: 0,
        opacity: 1,
      }}
      transition={{ ease: "easeInOut", duration: 0.75, delay: delay / 250 }}
    >
      <Link href={url} className="block" target="_blank">
        <Image
          src={TestImage}
          alt="Project Image"
          className="w-full transition-transform duration-700 group-hover:scale-105"
          loading="lazy"
          placeholder="blur"
        />
      </Link>
    </motion.div>
  );
};

const testProjects = [
  {
    url: "https://google.com",
  },
  {
    url: "https://google.com",
  },
];

const Index: NextPage<IndexPageProps> = () => {
  return (
    <>
      <Head>
        <title>Ryan Spacone — Director of Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4">
        {testProjects.map((project, i) => (
          <ProjectCard url={project.url} key={i} delay={i * 100} />
        ))}
      </div>
    </>
  );
};

export default Index;

export const getStaticProps = () => {
  return {
    props: {},
  };
};
