import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import { ProjectCard } from "../components/project-card/ProjectCard";

type IndexPageProps = InferGetStaticPropsType<typeof getStaticProps>;

const testProjects = [
  {
    slug: "test1",
  },
  {
    slug: "test2",
  },
];

const Index: NextPage<IndexPageProps> = () => {
  return (
    <>
      <Head>
        <title>Ryan Spacone — Director of Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4">
        {testProjects.map((project) => (
          <ProjectCard
            href={{
              pathname: "/projects/[slug]",
              query: { slug: project.slug },
            }}
            key={project.slug}
            projectTitle="Project"
          />
        ))}
      </div>
    </>
  );
};

export default Index;

export const getStaticProps: GetStaticProps = () => {
  return {
    props: {},
  };
};
