import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TestImage from "../../public/image.webp";

type IndexPageProps = InferGetStaticPropsType<typeof getStaticProps>;

const ProjectCard = ({
  url,
  projectTitle,
}: {
  url: string;
  projectTitle: string;
}) => {
  return (
    <div className="group overflow-hidden">
      <Link href={url} target="_blank" aria-label={projectTitle}>
        <Image
          src={TestImage}
          alt="Project Image"
          className="w-full transition-transform duration-700 group-hover:scale-105"
          placeholder="blur"
        />
        <span className="sr-only">{projectTitle}</span>
      </Link>
    </div>
  );
};

const testProjects = [
  {
    url: "https://google.com",
  },
  {
    url: "https://google.com",
  },
];

const Index: NextPage<IndexPageProps> = () => {
  return (
    <>
      <Head>
        <title>Ryan Spacone — Director of Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4">
        {testProjects.map((project, i) => (
          <ProjectCard url={project.url} key={i} projectTitle="Project" />
        ))}
      </div>
    </>
  );
};

export default Index;

export const getStaticProps: GetStaticProps = () => {
  return {
    props: {},
  };
};
